site_name: 'Bristol Flight Lab docs'
theme: 
  name: material
  logo: assets/logo.png
  palette:
    theme: flightlab
plugins:
  - search
  - literate-nav:
       nav_file: index.md
       implicit_index: true
