site_name: 'Bristol Flight Lab docs'
theme: 
  name: material
  logo: assets/logo.png
  palette:
    primary: '#B01C2E'
plugins:
  - search
  - literate-nav:
       nav_file: index.md
       implicit_index: true
